repository: pqsec/pqsec.github.io
theme: jekyll-theme-cayman

title: PQSEC.ORG
description: Ignat Korchagin
google_analytics: UA-124589907-1

github:
  is_project_page: false

plugins:
  - jekyll-sitemap
